services:
  frontend:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    environment:
      - NOTIFICATIONS_URL=${NOTIFICATIONS_URL}