services:
  frontend:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    environment:
      - NOTIFICATIONS_URL=http://localhost:8000 